# Generated by Django 2.2 on 2020-05-08 22:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('city_name', models.CharField(max_length=10, verbose_name='城市名')),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程信息',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('orgname', models.CharField(default='', max_length=20, verbose_name='机构名称')),
                ('orglable', models.CharField(default='', max_length=200, verbose_name='机构标签')),
                ('orgtype', models.CharField(choices=[('jg', '培训机构'), ('gr', '个人'), ('gx', '高校')], default='', max_length=20, verbose_name='机构类别')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('read_nums', models.IntegerField(default=0, verbose_name='收藏数')),
                ('orgaddress', models.CharField(default='', max_length=100, verbose_name='机构地址')),
                ('people_nums', models.IntegerField(default=0, verbose_name='学习人数')),
                ('class_nums', models.IntegerField(default=0, verbose_name='课程数')),
                ('orgauth', models.BooleanField(default=False, verbose_name='是否认证')),
                ('orggold', models.BooleanField(default=False, verbose_name='是否金牌')),
                ('orgimage', models.ImageField(upload_to='org/%Y/%m', verbose_name='logo')),
                ('city', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organizations.City', verbose_name='所在城市')),
            ],
            options={
                'verbose_name': '教育机构',
                'verbose_name_plural': '教育机构',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('teaname', models.CharField(default='', max_length=20, verbose_name='教师名')),
                ('workyear', models.IntegerField(default=0, verbose_name='工作年限(年)')),
                ('position', models.CharField(default='教师', max_length=20, verbose_name='公司职位')),
                ('Characteristic', models.CharField(default='', max_length=200, verbose_name='特点')),
                ('company', models.CharField(default='', max_length=20, verbose_name='就职公司')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('collection_nums', models.IntegerField(default=0, verbose_name='收藏数')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('image', models.ImageField(upload_to='teacher/%Y/%m', verbose_name='头像')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.CourseOrg', verbose_name='所属机构')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
            },
        ),
    ]
